GET http://localhost:3333/post

###

GET http://localhost:3333/post/1

###

POST http://localhost:3333/post
Content-Type: application/json

{
  "title": "Post do Fulano",
  "content": "Novo conteúdo adicionado!",
  "authorId": 1
}

###

PUT http://localhost:3333/post/1
Content-Type: application/json

{
  "title": "Post do Cicrano",
  "content": "Novo conteúdo adicionado!",
  "authorId": 1
}

###

DELETE http://localhost:3333/post/2